[tool.black]
line-length = 100
target-version = ["py39", "py310", "py311", "py312", "py313"]
exclude = '''
/(
  \.git
| \.venv
| \.dvc
| \.ipynb_checkpoints
| mlruns
| models
| artifacts
| data/processed
| __pycache__
)/
'''

[tool.isort]
profile = "black"
line_length = 100
skip = [".venv", ".git", ".dvc", "mlruns", "models", "artifacts", "data/processed", "__pycache__"]