name: docker build & push

on:
  push:
    branches: [ "main" ]          
    tags:     [ "v*.*.*" ]        

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # main -> latest
      - name: Build & push (latest)
        if: startsWith(github.ref, 'refs/heads/')
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/credit-api:latest

      # tag -> <tag> + latest
      - name: Build & push (tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/credit-api:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/credit-api:${{ github.ref_name }}